### ISSUE TITLE
"New Games" and "Recommended" are broken

### ISSUE THREAD

**Issue by TheUniKian** [carcaschoi/tinfoil-json#18]
Recently bought some games and their DLC, but I cant access the DLC on the Luffshop. It appears that the "New Games" Section is filled with everything that used to be filling the "Recommended" section, and "Recommended only has Super Mario 64 v8. Is there a way to fix it? Videos from just a few days ago show it working fine, and deleting locations.conf and retrying seems to have gotten me nowhere.

**Comment by carcaschoi** [comment]
https://rentry.co/reDUMPSHOPOAUTH

**Comment by Tigjsk** [comment]
Hey there please fix luffshop master carcaschoi please I'm begging you a lot of new games right now. Please tell us when will this be fix? Always download failed master..please enlighten us. Thanks

**Comment by Tigjsk** [comment]
@carcaschoi please help us.. download failed in luffshop for 3 days..please fix Master

**Comment by carcaschoi** [comment]
Follow the guide: https://rentry.co/reDUMPSHOPOAUTH

**Comment by TheUniKian** [comment]
> https://rentry.co/reDUMPSHOPOAUTH
> Follow the guide: https://rentry.co/reDUMPSHOPOAUTH

I have done this, it worked, however after a few hours Tinfoil stopped booting. After deleting all of tinfoils files and making sure it would work again it just stopped working. I have remade the credentials, remade the token, and reinserted the config and it is still broken, even after multiple tries. All I have is what I assume are the backup games like Sonic 1&2, some gameboy emulators, and Youtube 2.0.0.

Do you have an explanation for this?

**Comment by carcaschoi** [comment]
server are down for a little time

**Comment by Tigjsk** [comment]
@carcaschoi  does it mean luffshop will be down forever?

**Comment by trillyg** [comment]
> @carcaschoi does it mean luffshop will be down forever?

use awoo installer and download your nsp over usb for time being.

**Comment by carcaschoi** [comment]
the shop should come back now
