### ISSUE TITLE
Shop dont show up anything

### ISSUE THREAD

**Issue by Marietuno** [carcaschoi/tinfoil-json#19]
Is it the shop down currently?

**Comment by TheUniKian** [comment]
All shops are down, while they were working earlier today, it might've been a fluke

**Comment by carcaschoi** [comment]
servers are down for a little time

**Comment by Marietuno** [comment]
> servers are down for a short

tell me if u need some help ;)

**Comment by dbtuckey** [comment]
Are the servers still down? How can I see if they are?

**Comment by Zulptr** [comment]
> servers are down for a short time

till now shop is down

**Comment by carcaschoi** [comment]
the shop should come back now
