### ISSUE TITLE
There are only homebrew apps available at Luffshop rn

### ISSUE THREAD

**Issue by AexHar** [carcaschoi/tinfoil-json#20]
Hello, I just wanted to report that games arent showing up on Luffshop and that only homebrew games are available
Ps: I did set up Oauth

**Comment by notHiks** [comment]
stealthshop closed down so I guess expected

**Comment by carcaschoi** [comment]
source server down

**Comment by RealMimikyu** [comment]
its downloading games again on my switch so i guess its up for now

**Comment by Zulptr** [comment]
> source server down

till now down??

**Comment by carcaschoi** [comment]
the shop should come back now
