### ISSUE TITLE
Shop is down, no games showing

### ISSUE THREAD

**Issue by Zillygurt31** [carcaschoi/tinfoil-json#21]
No games showing on shop, can’t install or download any games. I have completed the Oauth Google successfully, still no games showing in shop

**Comment by Zulptr** [comment]
Same with me.no new game only some apps

**Comment by Batxif** [comment]
Same for me.

**Comment by afghn** [comment]
我也是

**Comment by carcaschoi** [comment]
the shop should come back now

**Comment by Zulptr** [comment]
till  now shop not yet have new games
