### ISSUE TITLE
Not loading new games on tinfoil

### ISSUE THREAD

**Issue by bocard80** [carcaschoi/tinfoil-json#22]
When loading into tinfoil no games are listed by luffshop in New games section any longer

**Comment by Zulptr** [comment]
![Uploading 48209149-2946-42D5-A6BE-35D38B56A047.jpeg…]()

**Comment by Zulptr** [comment]
yes not yet opem

**Comment by carcaschoi** [comment]
Please read luffshop notes

**Comment by carcaschoi** [comment]
Known issue #24
