### ISSUE TITLE
Shop are broken

### ISSUE THREAD

**Issue by unnnnny** [carcaschoi/tinfoil-json#23]
Shop is fixed but you cannot download game on it

**Comment by unnnnny** [comment]
Shop is fixed but you cannot download the game

**Comment by Zulptr** [comment]
> Shop is fixed but you cannot download game on it

just open them new game still
have no new games

**Comment by carcaschoi** [comment]
Please read luffshop notes

**Comment by carcaschoi** [comment]
known issue #24
