### ISSUE TITLE
There is one free shop you can use

### ISSUE THREAD

**Issue by unnnnny** [carcaschoi/tinfoil-json#29]
While waiting our beloved tinfoil shop luffshop stable, you can use jits.site. But unfortunately unlike luffshop or any other shop before this time jits.site use google drive storage instead the switch storage. so you can't download games that are more than 15gb unless you buy extra storage if the time runs out the storage will return to 15gb again and it's very annoying. I hope luffshop will be stable again soon

**Comment by carcaschoi** [comment]
switch.teknik.app is stable again

**Comment by AMSNX** [comment]
you can send tutorial or teach how i can make this forwarder like luffshop?
