### ISSUE TITLE
UnderPrivileged Shop downloads failed

### ISSUE THREAD

**Issue by FantashiS** [carcaschoi/tinfoil-json#30]
Hi, I have Gdrive auth set up and UnderPrivileged Shop is showing contents. But every time I try to download something it instantly fails. Is there any problem with the shop, or something else that I have to do before the download?

**Comment by trentech** [comment]
Same issue

**Comment by xKugel** [comment]
Same issue, logging file forbidden and invalid psf0 magic

**Comment by FantashiS** [comment]
Somehow it fixed itself, the download is working now.

**Comment by FantashiS** [comment]
Somehow it fixed itself, the download is working now.

**Comment by SwitchP** [comment]
> Somehow it fixed itself, the download is working now.

@FantashiS game downloads are only working from nekoshop and teknik.app shop, undershop has not been updated in a year
