### ISSUE TITLE
Oauth Guide is down

### ISSUE THREAD

**Issue by AkumaNoYami** [carcaschoi/tinfoil-json#31]
(optional & recommended) You have to set up Oauth if you cannot download 「something」 from tinfoil -> Guide: https://bit.ly/38HEr48  

can you reup the guide?

**Comment by carcaschoi** [comment]
It is not down yet

**Comment by Zulptr** [comment]
the new game side not display

**Comment by SwitchP** [comment]
> The Video is down
 @AkumaNoYami 

video is available in titz and nekodrive discords
