### ISSUE TITLE
the shop is lacking most of the game 

### ISSUE THREAD

**Issue by kimito1R** [carcaschoi/tinfoil-json#33]
i'm sorry but the new games tab lacks alot of the game at first it was fine then for some reason it didn't work anymore the next it came back lack most of the games

**Comment by EgorkZe** [comment]
The same for me

**Comment by SwitchP** [comment]
This "shop" has never had any games.

**Comment by PeaceMaker2001** [comment]
You need to get the teknik shop theme. Don't ask me why, it's just how it is. Once you download the theme and copy it into your themes folder within your tinfoil directory on your SD card (/switch/tinfoil/themes), you can select it by going into Options -> Theme, and then Press A and scroll down till you see 'teknik_default' and select it, restart Tinfoil and there you go...

**Comment by Zulptr** [comment]
> 
please share the theme link

**Comment by arch-box** [comment]
> please share the theme link

There is a message popup pointing you to where the themes are located, although I understand it may be difficult to retype it from the tinfoil screen. Here is a direct link from the motd: https://discord.gg/teknik

There is a note next to the files saying to not rehost the teknik_ themes, so I wouldn't be able to attach the files directly here. Have a nice day!

**Comment by olivatooo** [comment]
all other shops are off?
