### ISSUE TITLE
Update on teknik.app

### ISSUE THREAD

**Issue by lmm1191** [carcaschoi/tinfoil-json#35]
Protocol: HTTPS
Host: Teknik.app

NOTE: Please advise that user needs to download the teknik-themes for tinfoil and change the theme of their tinfoil to any of the theme from the zip. That's the only time it will work.

Add on request: Do you know about Devshop? They said it's up but I can't find any details about it. Thanks

**Comment by carcaschoi** [comment]
fixed and I added a message to advise other users to use teknik theme
btw I know devshop and it is not maintained by me. Therefore, I cannot provide any support about devshop

**Comment by Zulptr** [comment]
The new game now disappear

**Comment by Zulptr** [comment]
> Protocol: HTTPS Host: Teknik.app
> 
> NOTE: Please advise that user needs to download the teknik-themes for tinfoil and change the theme of their tinfoil to any of the theme from the zip. That's the only time it will work.
> 
> Add on request: Do you know about Devshop? They said it's up but I can't find any details about it. Thanks

this not work

**Comment by lmm1191** [comment]
It works on my end. They need to make sure to use teknik theme. And the host should be teknik.app instead of switch.teknik.app
