### ISSUE TITLE
All servers are down? 

### ISSUE THREAD

**Issue by castorfou** [carcaschoi/tinfoil-json#37]
Luffshop is automatically adding 4 sources
Teknik.app, nekoshop, titz, ecchi save. 

But no games are listed (and the game section is not visible)
Search is returning no result.

Is it the same for you or coming from my config?

**Comment by phoberus** [comment]
For me it also doesn't work since some weeks. Some of my games are in the "not completed" tab, but they work as they should.
@carcaschoi Is this a problem with the new tinfoil update?
Do we need to reinstall it? Or are the shops offline?

**Comment by carcaschoi** [comment]
get access key from teknik discord
https://teknik.app

**Comment by castorfou** [comment]
I got a key. Does it mean we have to insert a new shop from teknik but we cannot use your json for that. Just to be sure
